/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;

/**
 *
 * @author Butrint Bajrami
 */
public class Restaurant_Menu_Choosable extends javax.swing.JFrame {

  
    public Restaurant_Menu_Choosable() {
        FlatLightLaf.setup();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supply_panel = new javax.swing.JButton();
        supply_panel1 = new javax.swing.JButton();
        object_panel = new javax.swing.JButton();
        supply_panel3 = new javax.swing.JButton();
        supply_panel4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(237, 200, 119));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chose");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        supply_panel.setBackground(new java.awt.Color(237, 203, 118));
        supply_panel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        supply_panel.setForeground(new java.awt.Color(0, 0, 0));
        supply_panel.setText("Supply");
        supply_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supply_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supply_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supply_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supply_panelMouseExited(evt);
            }
        });
        supply_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_panelActionPerformed(evt);
            }
        });

        supply_panel1.setBackground(new java.awt.Color(237, 203, 118));
        supply_panel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supply_panel1.setForeground(new java.awt.Color(0, 0, 0));
        supply_panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supply_panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supply_panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supply_panel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supply_panel1MouseExited(evt);
            }
        });
        supply_panel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_panel1ActionPerformed(evt);
            }
        });

        object_panel.setBackground(new java.awt.Color(237, 203, 118));
        object_panel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        object_panel.setForeground(new java.awt.Color(0, 0, 0));
        object_panel.setText("Objects");
        object_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        object_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        object_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                object_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                object_panelMouseExited(evt);
            }
        });
        object_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                object_panelActionPerformed(evt);
            }
        });

        supply_panel3.setBackground(new java.awt.Color(237, 203, 118));
        supply_panel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supply_panel3.setForeground(new java.awt.Color(0, 0, 0));
        supply_panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supply_panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supply_panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supply_panel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supply_panel3MouseExited(evt);
            }
        });
        supply_panel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_panel3ActionPerformed(evt);
            }
        });

        supply_panel4.setBackground(new java.awt.Color(237, 203, 118));
        supply_panel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supply_panel4.setForeground(new java.awt.Color(0, 0, 0));
        supply_panel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        supply_panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supply_panel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supply_panel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supply_panel4MouseExited(evt);
            }
        });
        supply_panel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supply_panel4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(supply_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(supply_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supply_panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(object_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(supply_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(supply_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(object_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supply_panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supply_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supply_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supply_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panelMouseEntered
        supply_panel.setForeground(Color.WHITE);
    }//GEN-LAST:event_supply_panelMouseEntered

    private void supply_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panelMouseExited
        supply_panel.setForeground(Color.BLACK);
    }//GEN-LAST:event_supply_panelMouseExited

    private void supply_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_panelActionPerformed
       Add_Supply as = new Add_Supply();
       as.show();
       dispose();
       
    }//GEN-LAST:event_supply_panelActionPerformed

    private void supply_panel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel1MouseEntered

    private void supply_panel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel1MouseExited

    private void supply_panel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_panel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel1ActionPerformed

    private void object_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_object_panelMouseEntered
        object_panel.setForeground(Color.WHITE);
    }//GEN-LAST:event_object_panelMouseEntered

    private void object_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_object_panelMouseExited
        object_panel.setForeground(Color.BLACK);
    }//GEN-LAST:event_object_panelMouseExited

    private void object_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_object_panelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_object_panelActionPerformed

    private void supply_panel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel3MouseEntered

    private void supply_panel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panel3MouseExited
        
    }//GEN-LAST:event_supply_panel3MouseExited

    private void supply_panel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_panel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel3ActionPerformed

    private void supply_panel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel4MouseEntered

    private void supply_panel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supply_panel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel4MouseExited

    private void supply_panel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supply_panel4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supply_panel4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Menu_Choosable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Menu_Choosable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Menu_Choosable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Menu_Choosable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_Menu_Choosable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton object_panel;
    private javax.swing.JButton supply_panel;
    private javax.swing.JButton supply_panel1;
    private javax.swing.JButton supply_panel3;
    private javax.swing.JButton supply_panel4;
    // End of variables declaration//GEN-END:variables
}
